squash

diff --git a/.github/actions/setup-job/action.yml b/.github/actions/setup-job/action.yml
--- a/.github/actions/setup-job/action.yml
+++ b/.github/actions/setup-job/action.yml
@@ -26,12 +26,12 @@ runs:
         submodules: recursive
         path: ${{ inputs.path }}
 
-    - name: 🧪 Check Required Tools
-      run: |
-        echo "🔍 Verifying tools..."
-        command -v tar >/dev/null 2>&1 && tar --version || { echo "❌ tar not found"; exit 1; }
-        command -v pip3 >/dev/null 2>&1 && pip3 --version || { echo "❌ pip3 not found"; exit 1; }
-      shell: bash
+    # - name: 🧪 Check Required Tools
+    #   run: |
+    #     echo "🔍 Verifying tools..."
+    #     command -v tar >/dev/null 2>&1 && tar --version || { echo "❌ tar not found"; exit 1; }
+    #     command -v pip3 >/dev/null 2>&1 && pip3 --version || { echo "❌ pip3 not found"; exit 1; }
+    #   shell: bash
 
     - name: 📦 Download Build Artifact
       if: ${{ inputs.build-artifact-name != '' }}
@@ -53,6 +53,20 @@ runs:
         name: ${{ inputs.wheel-artifact-name }}
         path: ${{ inputs.path }}
 
+    - name: "Install Cached Python Dependencies"
+      uses: getsentry/action-setup-venv@v2.1.1
+      id: venv
+      with:
+        python-version: ${{ inputs.python-version }}
+        venv-dir: ${{ github.workspace }}/python_env
+        cache-dependency-path: |
+          tt_metal/python_env/requirements-dev.txt
+          docs/requirements-docs.txt
+          tests/sweep_framework/requirements-sweeps.txt
+          pyproject.toml
+          create_venv.sh
+        install-cmd: ./create_venv.sh
+
     - name: 💿 Install Wheel
       if: ${{ inputs.wheel-artifact-name != '' }}
       working-directory: ${{ inputs.path }}
@@ -62,6 +76,7 @@ runs:
         ls -la
         WHEEL_FILENAME=$(ls -1 *.whl)
         echo "📦 Installing $WHEEL_FILENAME"
+        source ${{ github.workspace }}/python_env/bin/activate
         pip3 install "$WHEEL_FILENAME"
       shell: bash
 
