8B DP Test

diff --git a/.github/workflows/vllm-nightly-tests-impl.yaml b/.github/workflows/vllm-nightly-tests-impl.yaml
--- a/.github/workflows/vllm-nightly-tests-impl.yaml
+++ b/.github/workflows/vllm-nightly-tests-impl.yaml
@@ -25,19 +25,9 @@ jobs:
       matrix:
         test-group: [
           {
-            name: "[T3K] Llama-3.1-8B-Instruct",
+            name: "[TG] Llama-3.1-8B-Instruct",
             arch: wormhole_b0,
             model: "meta-llama/Llama-3.1-8B-Instruct",
-            server_timeout: 5,
-            benchmark_timeout: 5,
-            runner-label: config-t3000,
-            co-owner-1_id: U08E1JCDVNX, # Pavle Petrovic
-            co-owner-2_id: U08CEGF78ET, # Salar Hosseini Khorasgani
-          },
-          {
-            name: "[TG] Llama-3.3-70B-Instruct",
-            arch: wormhole_b0,
-            model: "meta-llama/Llama-3.3-70B-Instruct",
             server_timeout: 35,
             benchmark_timeout: 10,
             runner-label: config-tg,
@@ -106,7 +96,7 @@ jobs:
             "config-tg")
               export MESH_DEVICE="TG"
               export TT_LLAMA_TEXT_VER="llama3_subdevices"
-              OVERRIDE_TT_CONFIG=(--override-tt-config '{"dispatch_core_axis": "col", "sample_on_device_mode": "all", "fabric_config": "FABRIC_1D"}')
+              OVERRIDE_TT_CONFIG=(--override-tt-config '{"data_parallel": 16}')
               ;;
             *)
               echo "❌ Unsupported runner-label: ${matrix.test-group.runner-label}"
@@ -152,7 +142,7 @@ jobs:
           cat "${{ env.server_log }}"
           exit 1
 
-      - name: 📐 Run benchmark
+      - name: 📐 Run benchmark 128
         timeout-minutes: ${{ matrix.test-group.benchmark_timeout }}
         run: |
           python3 vllm/benchmarks/benchmark_serving.py \
@@ -167,6 +157,84 @@ jobs:
             --save-result \
             --result-filename output/vllm_result.json \
             2>&1 | tee ${{ env.benchmark_log }}
+
+          # If the backend fails, the benchmark will still complete successfully but with all-zero results.
+          # It will contain a warning message, though
+          warning_message="All requests failed"
+          if grep -q "$warning_message" "${{ env.benchmark_log }}"; then
+            echo "❌ All requests failed, here's the server log:"
+            printf "\n\n----------- Server Log -----------\n\n"
+            cat "${{ env.server_log }}"
+            exit 1
+          fi
+
+      - name: 📐 Run benchmark 1k
+        timeout-minutes: ${{ matrix.test-group.benchmark_timeout }}
+        run: |
+          python3 vllm/benchmarks/benchmark_serving.py \
+            --backend vllm \
+            --model ${{ matrix.test-group.model }} \
+            --dataset-name random \
+            --num-prompts 32 \
+            --random-input-len 950 \
+            --random-output-len 950 \
+            --ignore-eos \
+            --percentile-metrics ttft,tpot,itl,e2el \
+            --save-result \
+            --result-filename output/vllm_result.json \
+            2>&1 | tee -a ${{ env.benchmark_log }}
+
+          # If the backend fails, the benchmark will still complete successfully but with all-zero results.
+          # It will contain a warning message, though
+          warning_message="All requests failed"
+          if grep -q "$warning_message" "${{ env.benchmark_log }}"; then
+            echo "❌ All requests failed, here's the server log:"
+            printf "\n\n----------- Server Log -----------\n\n"
+            cat "${{ env.server_log }}"
+            exit 1
+          fi
+
+      - name: 📐 Run benchmark 2k
+        timeout-minutes: ${{ matrix.test-group.benchmark_timeout }}
+        run: |
+          python3 vllm/benchmarks/benchmark_serving.py \
+            --backend vllm \
+            --model ${{ matrix.test-group.model }} \
+            --dataset-name random \
+            --num-prompts 32 \
+            --random-input-len 1900 \
+            --random-output-len 1900 \
+            --ignore-eos \
+            --percentile-metrics ttft,tpot,itl,e2el \
+            --save-result \
+            --result-filename output/vllm_result.json \
+            2>&1 | tee -a ${{ env.benchmark_log }}
+
+          # If the backend fails, the benchmark will still complete successfully but with all-zero results.
+          # It will contain a warning message, though
+          warning_message="All requests failed"
+          if grep -q "$warning_message" "${{ env.benchmark_log }}"; then
+            echo "❌ All requests failed, here's the server log:"
+            printf "\n\n----------- Server Log -----------\n\n"
+            cat "${{ env.server_log }}"
+            exit 1
+          fi
+
+      - name: 📐 Run benchmark 4k
+        timeout-minutes: ${{ matrix.test-group.benchmark_timeout }}
+        run: |
+          python3 vllm/benchmarks/benchmark_serving.py \
+            --backend vllm \
+            --model ${{ matrix.test-group.model }} \
+            --dataset-name random \
+            --num-prompts 32 \
+            --random-input-len 3800 \
+            --random-output-len 3800 \
+            --ignore-eos \
+            --percentile-metrics ttft,tpot,itl,e2el \
+            --save-result \
+            --result-filename output/vllm_result.json \
+            2>&1 | tee -a ${{ env.benchmark_log }}
 
           # If the backend fails, the benchmark will still complete successfully but with all-zero results.
           # It will contain a warning message, though
