Fail the job if backend failed, but benchmark completed

diff --git a/.github/workflows/vllm-nightly-tests-impl.yaml b/.github/workflows/vllm-nightly-tests-impl.yaml
--- a/.github/workflows/vllm-nightly-tests-impl.yaml
+++ b/.github/workflows/vllm-nightly-tests-impl.yaml
@@ -145,6 +145,8 @@ jobs:
       - name: 📐 Run benchmark
         timeout-minutes: ${{ matrix.test-group.benchmark_timeout }}
         run: |
+          behchmark_log="./output/vllm_benchmark.log"
+
           python3 vllm/benchmarks/benchmark_serving.py \
             --backend vllm \
             --model ${{ matrix.test-group.model }} \
@@ -156,7 +158,15 @@ jobs:
             --percentile-metrics ttft,tpot,itl,e2el \
             --save-result \
             --result-filename output/vllm_result.json \
-            2>&1 | tee output/vllm_benchmark.log
+            2>&1 | tee $benchmark_log
+
+          # If the backend fails, the benchmark will still complete successfully but with all-zero results.
+          # It will contain a warning message, though
+          warning_message="All requests failed"
+          if grep -q $warning_message $behchmark_log; then
+            echo "❌ All requests failed, check out vllm_server.log"
+            exit 1
+          fi
 
       - name: 🧹 Cleanup server process
         if: always()
